name: workflow

on:
  

  workflow_dispatch:
    inputs:
      Value1:
        description: 'First Name'
        required: true
        default: '--'
        
        

      Value2:
        description: 'Last Name'
        required: true
        default: '--'
        
        

  
jobs:
  run-python-test:
    runs-on: ubuntu-latest
    steps:
  
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
  
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
  
      - name: Execute Test Script
        run: input_value=${{ github.event.inputs.Value1 }}${{ github.event.inputs.Value2 }} python3 simple/simple.py
